const DEFAULT_PRODUCTS = [
  {
    code: "Br-0011",
    category: "Serum",
    nameKor: "바를 수딩 베리어 세럼",
    nameEng: "Barle Soothing Barrier Serum",
    barcode: "8800259230010",
    size: "50ml",
    cartonQty: 50,
    cartonSize: "46.5*24.2*19.5",
    cbm: 0.02194335,
    shelfLife: 36,
    moq: 50,
    srpUsd: 29.59,
    fobRate: 0.29,
    fobUsd: 8.5811,
  },
  {
    code: "Br-0010",
    category: "Toner Pad",
    nameKor: "바를 시카 밤부 토너 패드",
    nameEng: "Barle Cica Bamboo Toner Pads",
    barcode: "8800259230003",
    size: "200ml, 70 sheets",
    cartonQty: 50,
    cartonSize: "42.5*28*22.5",
    cbm: 0.026775,
    shelfLife: 24,
    moq: 50,
    srpUsd: 26.15,
    fobRate: 0.29,
    fobUsd: 7.5835,
  },
  {
    code: "Br-0012",
    category: "Cleansing Balm",
    nameKor: "바를 차콜 멜팅 클렌징 밤",
    nameEng: "Barle Charcoal Melting Cleansing Balm",
    barcode: "8800259230034",
    size: "100ml",
    cartonQty: 40,
    cartonSize: "42.5*37*23",
    cbm: 0.0361675,
    shelfLife: 30,
    moq: 50,
    srpUsd: 24.09,
    fobRate: 0.29,
    fobUsd: 6.9861,
  },
  {
    code: "Br-0013",
    category: "Sunblock",
    nameKor: "바를 아쿠아 브리즈 선블럭",
    nameEng: "Barle Aqua Breeze Sunblock",
    barcode: "8800259230041",
    size: "50ml",
    cartonQty: 80,
    cartonSize: "44*25.5*21",
    cbm: 0.023562,
    shelfLife: 30,
    moq: 50,
    srpUsd: 26.84,
    fobRate: 0.29,
    fobUsd: 7.7836,
  },
  {
    code: "Br-0014-03",
    category: "Lipbalm",
    nameKor: "바를 글로이 플럼핑 밤 멜팅클리어",
    nameEng: "Barle Glowy Plumping Balm Melting Clear",
    barcode: "8800259230058",
    size: "3.3g",
    cartonQty: 550,
    cartonSize: "60*31.5*32",
    cbm: 0.06048,
    shelfLife: 24,
    moq: 20,
    srpUsd: 7.5,
    fobRate: 0.29,
    fobUsd: 2.175,
  },
  {
    code: "Br-0014",
    category: "Lipbalm",
    nameKor: "바를 글로이 플럼핑 밤 멜팅핑크",
    nameEng: "Barle Glowy Plumping Balm Melting Pink",
    barcode: "8800259230102",
    size: "3.3g",
    cartonQty: 550,
    cartonSize: "60*31.5*32",
    cbm: 0.06048,
    shelfLife: 24,
    moq: 20,
    srpUsd: 7.5,
    fobRate: 0.29,
    fobUsd: 2.175,
  },
  {
    code: "Br-0014-02",
    category: "Lipbalm",
    nameKor: "바를 글로이 플럼핑 밤 멜팅코랄",
    nameEng: "Barle Glowy Plumping Balm Melting Coral",
    barcode: "8800259230119",
    size: "3.3g",
    cartonQty: 550,
    cartonSize: "60*31.5*32",
    cbm: 0.06048,
    shelfLife: 24,
    moq: 20,
    srpUsd: 7.5,
    fobRate: 0.29,
    fobUsd: 2.175,
  },
];

const DEFAULT_TERMS_EXPORT_LINES = [
  "1. FDA COMPLIANCE : All products must meet FDA regulations",
  "2. PRODUCT LABEL : ENGLISH LABELLING REQUIRED",
  "3. PRICE TERMS : USD FOB, Busan, Korea",
  "4. TERMS OF PAYMENT : T/T (30% advance / 70% before shipment)",
  "5. SHIPMENT : 4-6 weeks after order confirmation",
  "6. INSURANCE : To be covered by buyer",
];

const DEFAULT_TERMS_DOMESTIC_LINES = [
  "• 상기 공급단가는 VAT 별도 기준입니다.",
  "• 견적 유효기간은 견적일로부터 30일입니다.",
  "• 최소 발주수량(MOQ)은 제품 및 거래 조건에 따라 별도 협의합니다.",
  "• 결제조건은 발주 시 100% 선입금을 기본으로 하며, 별도 협의 가능합니다.",
  "• 입금 및 재고 확인 후 출고되며, 납기 일정은 발주 시 확정됩니다.",
  "• 배송비 및 대량 발주·프로모션 조건은 별도 협의합니다.",
  "• 판매 프로모션 및 가격 운영은 브랜드 정책에 따라 사전 협의가 필요할 수 있습니다.",
];

function buildDefaultTermPresets() {
  return [
    { id: "preset-1", name: "해외", lines: [...DEFAULT_TERMS_EXPORT_LINES] },
    { id: "preset-2", name: "국내", lines: [...DEFAULT_TERMS_DOMESTIC_LINES] },
  ];
}

const DEFAULT_CHANNELS = [
  {
    id: "KR-OLIVE",
    name: "올리브영",
    currency: "KRW",
    currencySymbol: "₩",
    defaultFobRate: 0.35,
    terms: buildDefaultTermPresets(),
  },
  {
    id: "CN",
    name: "중국",
    currency: "USD",
    currencySymbol: "$",
    defaultFobRate: 0.29,
    terms: buildDefaultTermPresets(),
  },
  {
    id: "US",
    name: "미국",
    currency: "USD",
    currencySymbol: "$",
    defaultFobRate: 0.32,
    terms: buildDefaultTermPresets(),
  },
];

const DEFAULT_EXCHANGE_RATE = 1350;
const DEFAULT_JPY_PER_USD = 150;

const DEFAULT_SRP = {
  "Br-0011": { "KR-OLIVE": { krw: null, usd: null }, CN: { krw: null, usd: 29.59 }, US: { krw: null, usd: 32.0 } },
  "Br-0010": { "KR-OLIVE": { krw: null, usd: null }, CN: { krw: null, usd: 26.15 }, US: { krw: null, usd: 28.0 } },
  "Br-0012": { "KR-OLIVE": { krw: null, usd: null }, CN: { krw: null, usd: 24.09 }, US: { krw: null, usd: 26.0 } },
  "Br-0013": { "KR-OLIVE": { krw: null, usd: null }, CN: { krw: null, usd: 26.84 }, US: { krw: null, usd: 29.0 } },
  "Br-0014-03": { "KR-OLIVE": { krw: null, usd: null }, CN: { krw: null, usd: 7.5 }, US: { krw: null, usd: 8.5 } },
  "Br-0014": { "KR-OLIVE": { krw: null, usd: null }, CN: { krw: null, usd: 7.5 }, US: { krw: null, usd: 8.5 } },
  "Br-0014-02": { "KR-OLIVE": { krw: null, usd: null }, CN: { krw: null, usd: 7.5 }, US: { krw: null, usd: 8.5 } },
};
